Merge MI-108 with dev
MI-390/mRides-server pull request #7
Opened 2017-03-24 17:33 UTC by AlineTheAlien

Changed setGSD method to only accept a dynamic object from body

2017-03-29 15:44 UTC, AlineTheAlien commented
@nim442 Can you please review?

2017-04-02 20:57 UTC, nim442 requested changes

2017-04-02 20:57 UTC, nim442 commented on src/mRides-server/Controllers/UserController.cs
> +            //int newUserId = Convert.ToInt32(userId);
remove commented out code

2017-04-02 20:57 UTC, nim442 commented on src/mRides-server/Logic/UserCatalog.cs
> -            //User u = _context.Users.Find(userId);
👍

2017-04-03 02:43 UTC, AlineTheAlien commented on src/mRides-server/Controllers/UserController.cs
> +            //int newUserId = Convert.ToInt32(userId);
Good catch!

2017-04-03 02:43 UTC, AlineTheAlien commented
@nim442 I made the changes you requested, the branch is ready to merge.

2017-04-04 02:11 UTC, merged