Code for implementing user gender in database
MI-390/mRides-server pull request #8
Opened 2017-03-29 16:02 UTC by AlineTheAlien

Pull request includes the addition of a gender column in the User table, as well as the respective get and set methods in the UserController class to allow the app side to retrieve and update the gender of a user.

The set method takes a dynamic object with the following format: 

{
"userId": 8,
"userGender": "male"
}

2017-04-02 20:52 UTC, nim442 requested changes

2017-04-02 20:52 UTC, nim442 commented on src/mRides-server/Controllers/UserController.cs
> +        public string getGender(int id)
Since we get the whole user object(which already has this attribute) to populate the user profile, this method is redundant (YAGNI)

2017-04-02 20:52 UTC, nim442 commented on src/mRides-server/Logic/UserCatalog.cs
> +            User u = get(userId);
Same as the above comment

2017-04-02 20:52 UTC, nim442 commented on src/mRides-server/Logic/UserCatalog.cs
> +        {
We should have an updateUser method that would take care of any attribute updates rather than a method for each attribute

2017-04-03 02:31 UTC, AlineTheAlien commented on src/mRides-server/Logic/UserCatalog.cs
> +        {
Yes you're right, but we don't have the method at this point and have another method in the server for modifying an attribute and these are the only ones we will need in the application, so I don't think it's necessary right now

2017-04-03 02:39 UTC, AlineTheAlien commented on src/mRides-server/Controllers/UserController.cs
> +        public string getGender(int id)
Yeah I didn't realize it, I'll have to remove my changes from both app and server side then.

2017-04-04 02:11 UTC, merged